module.exports = {
  badWords: [
    // Indonesia - Hewan
    'anjing', 'anj', 'njing', 'anjg', 'ajg', 'njg', 'anying', 'anjeng', 'anjir', 'anjrit', 'anjay',
    'a njing', 'a.njing', 'an.jing', 'anj1ng', 'anj!ng', '@njing', 'anjinh', 'anjingg',
    'babi', 'bb', 'celeng', 'b4bi', 'bab1', 'b@bi', 'babik',
    'asu', 'asyu', 'asyuu', 'as.u', 'a.su',
    'monyet', 'mnyt', 'kunyuk', 'bajing', 'monyong', 'monyett', 'monyed',
    'dancuk', 'dancok', 'jancok', 'jancuk', 'jnck', 'jncuk', 'j4ncuk', 'jank0k',
    'cuki', 'cukimai', 'cukimay', 'cuk', 'cukk',
    'kadal', 'kecoa', 'tikus', 'buaya', 'bangkai', 'bangke',

    // Indonesia - Kotoran/Jorok
    'tai', 'taik', 'tokai', 'eeq', 'pantek', 'kampret', 'ngehe',
    't4i', 't@i', 'taimu', 'taik lo', 'ketaian',
    'b4ngke', 'bangkee', 'bngke',
    'setan', 'syetan', 'set4n', 's3tan', 'iblis', 'ibli5',
    'keparat', 'kprt', 'k3parat', 'kepar4t',
    'sialan', 'sial', 'siaalan', 's1al', 'sialn',
    'bajingan', 'bjngn', 'b4jingan', 'bajingann', 'bajngan',
    'brengsek', 'brgsek', 'br3ngsek', 'brengseck', 'brngsek',
    'kurang ajar', 'kurangajar', 'krnj', 'krngajr',
    'bedebah', 'b3debah', 'bddebah',
    'bajigur', 'bajigurl',
    'kampang', 'kmpng',
    'laknat', 'terkutuk', 'durjana', 'biadab',
    'mampus', 'mampos', 'm4mpus',
    'mati kau', 'matikau',
    'oon', 'ooon', 'oon berat',
    'najis', 'jorok',
    'tai kucing', 'taikucing',
    'sontoloyo', 'sontoloy0', 'santoloy',

    // Indonesia - Seksual/Alat Kelamin
    'kontol', 'kntl', 'kntol', 'kon', 'ntol', 'kontl',
    'k0ntol', 'k0nt0l', 'kont0l', 'konntol', 'k.o.n.t.o.l',
    'peler', 'pler', 'biji', 'titit', 'tiit', 't1tit',
    'puki', 'pukimak', 'kimak', 'puk1', 'puk!', 'puk1mak', 'p.u.k.i',
    'memek', 'mmk', 'mek', 'memk', 'pepek', 'ppk', 'itil',
    'm3mek', 'm.e.m.e.k', 'mem3k', 'memeq', 'p3pek', 'p.e.p.e.k',
    'jembut', 'jmbt', 'jembot', 'j3mbut',
    'tetek', 'toket', 'ttk', 't3tek', 't0ket', 'ttek', 'ttoket',
    'ngaceng', 'ngacer', 'ngac3ng',
    'susu', 'sus00',
    'bokong', 'pantat', 'bokep', 'porno',
    'dubur', 'anus', 'mesum', 'bugil', 'telanjang',
    'vagina', 'vulva', 'klitoris', 'kemaluan',
    'payudara', 'selangkangan',

    // Indonesia - Aktivitas Seksual
    'ngentot', 'ngntot', 'ngentd', 'ngntd', 'ngtd', 'ngewe', 'ngwe', 'ngw', 'ewean', 'kenthu',
    'ng3ntot', 'ng3nt0t', 'ngent0t', 'n.g.e.n.t.o.t', 'ngentod',
    'ng3we', 'ng.ewe', 'ng3w3', 'ewe', 'ewein', 'diewe',
    'colmek', 'coli', 'sange', 'sangean',
    'c0lmek', 'c.o.l.m.e.k', 'col1', 's4nge', 'sang3',
    'githok', 'ranjang', 'entot', 'ent0t',
    'perkosa', 'memperkosa', 'pemerkosaan',
    'cabul', 'pencabulan',
    'onani', 'masturbasi', 'ngocok',
    'blowjob', 'handjob', 'oral', 'sexting',

    // Indonesia - Profesi/Hinaan
    'perek', 'prk', 'lonte', 'lont', 'l0nte', 'sundel', 'jablay', 'jbly', 'pelacur', 'openbo', 'psk',
    'p3rek', 'per3k', 'l0nt3', 'lont3', 'l.o.n.t.e', 'sundal', 'sund4l',
    'jbl4y', 'jabley', 'j4blay', 'p3lacur', 'pel4cur',
    'bangsat', 'bgst', 'bgsat', 'bngst', 'bnst',
    'b4ngsat', 'bang5at', 'b.a.n.g.s.a.t', 'bangzat', 'bangs4t',
    'tolol', 'tll', 'toll', 'goblok', 'gblk', 'goblk', 'gblok', 'bego', 'dungu', 'idiot', 'bodoh', 'geblek', 'pekok',
    't0lol', 't.o.l.o.l', 'tol0l', 'tololll',
    'g0blok', 'gobl0k', 'g.o.b.l.o.k', 'goblokk', 'gbl0k',
    'b3go', 'beg0', 'd.u.n.g.u',
    'id10t', '1diot', 'idi0t', 'i.d.i.o.t',
    'b0doh', 'bod0h', 'b.o.d.o.h',
    'gila', 'gilaa', 'g1la', 'g!la', 'gilak', 'edan',
    'kafir', 'k4fir', 'kaf1r',
    'bloon', 'dongo', 'dodol', 'dongok',
    'kampungan', 'norak', 'barbar',
    'pengecut', 'pengkhianat', 'munafik', 'penipu',
    'preman', 'berandal', 'brandal', 'garong',
    'bejat', 'terlaknat', 'pecundang',
    'kutu kupret',
    'gajelas', 'ga jelas', 'gajls',
    'cebong', 'kadrun',
    'goblog', 'gobloog', 'g0blog',
    'sempak',

    // Hinaan SARA
    'kafir laknat', 'kafir bangsat',
    'china babi', 'cina babi',
    'pribumi babi', 'jawa babi', 'batak babi',
    'sunda babi', 'melayu babi', 'ambon babi', 'papua babi',
    'anjing cina', 'anjing china', 'anjing kafir',

    // Bahasa Jawa/Daerah
    'asem', 'cuk', 'cok',
    'matamu', 'mbahmu',
    'ndasmu', 'ndas', 'matane', 'ndhasmu',
    'pukimon',
    'nggapleki', 'kejet',
    'kirik', 'jebret',
    'gendheng', 'edan tenan',
    'setan alas', 'gableg',
    'gemblung', 'geblung', 'kenthir', 'kluthuk',
    'goblog tenan', 'bejad',
    'semprul', 'dhiancuk',
    'wedhus', 'pejwan',

    // Bahasa Sunda
    'belegug', 'beleguguh',
    'sia', 'maneh goblog', 'kepret',

    // Gaul Indonesia Modern
    'goblok lo', 'tolol lo', 'bodoh lo', 'bego lo',
    'anjing lo', 'bangsat lo', 'brengsek lo', 'keparat lo', 'sialan lo',
    'lu goblok', 'lu tolol', 'lu bodoh', 'lu anjing', 'lu babi',
    'lo brengsek', 'lo bangsat',
    'brengsek kau', 'goblok kau', 'tolol kau', 'anjing kau',
    'binatang lo', 'hewan lo',
    'dasar anjing', 'dasar babi', 'dasar goblok',
    'dasar tolol', 'dasar bangsat', 'dasar brengsek',
    'dasar hewan', 'dasar binatang', 'dasar pecundang',
    'gapunya otak', 'ga punya otak',
    'otakmu dimana', 'otak lo kemana',
    'gabisa mikir', 'ga bisa mikir',
    'goblog banget', 'goblok banget', 'bego banget',
    'tolol banget', 'bodoh banget',
    'bajingan ternak',
    'tukang bohong', 'pembohong',
    'maling', 'koruptor',

    // Kata Ancaman / Kekerasan
    'bunuh lo', 'bunuhlo',
    'aku bunuh lo', 'gue bunuh lo',
    'mau gue bunuh', 'bakalan mati lo',
    'matiin lo', 'hajar lo',
    'tonjok lo', 'tonjokin lo',
    'pukul lo', 'pukulin lo',
    'tampar lo', 'habisin lo',
    'musnahin lo', 'gebuk lo', 'gebukin lo',
    'aku sikat lo', 'gue sikat lo', 'gue habisi lo',

    // Inggris - Umum
    'fuck', 'fck', 'fcking', 'fucker', 'fucking', 'motherfucker', 'mf', 'mfs', 'fuk', 'fku',
    'f.u.c.k', 'fvck', 'phuck', 'fuxk', 'fucc', 'effing', 'fking', 'f2k',
    'fukk', 'f0ck', 'f0k', 'fack', 'fawk', 'fvk',
    'shit', 'bullshit', 'shitty', 'sh1t', 'shithole', 'shithead', 'dipshit', 'shitfaced',
    's.h.i.t', 'sht', 'shyt', 'shiit', 'shitt',
    'bitch', 'bitches', 'sonofabitch', 'b1tch', 'btch',
    'b!tch', 'b.i.t.c.h', 'bytch', 'biatch', 'beatch', 'bich', 'btich',
    'ass', 'asshole', 'assholes', 'dumbass', 'jackass',
    '@ss', 'a55', 'a.s.s', '@sshole', 'a55hole', 'dumb@ss', 'jack@ss', 'smartass',
    'asshat', 'assclown', 'asslicker', 'asskisser',
    'dick', 'dickhead', 'cock', 'cocksucker', 'penis', 'vagina',
    'd1ck', 'd!ck', 'dik', 'd.i.c.k', 'c0ck', 'c.o.c.k', 'kock', 'cockwomble',
    'p3nis', 'pen1s', 'p.e.n.i.s', 'v4gina', 'vag1na', 'vag',
    'pussy', 'cunt',
    'puss1', 'pvssy', 'kunt', 'cvnt',
    'slut', 'whore', 'hooker', 'prostitute',
    'slvt', 'wh0re', 'h00ker',
    'bastard', 'b4stard', 'b@stard', 'bstrd',
    'damn', 'damm', 'd4mn', 'dammit', 'goddamn', 'goddammit',
    'crap', 'cr4p', 'cr@p', 'crappy', 'bullcrap',
    'piss', 'p1ss', 'pissed', 'pissoff', 'pisser',
    'hell', 'wtf', 'stfu', 'gtfo', 'kys', 'kms',
    'moron', 'mor0n', 'dumbass', 'dumb', 'stupid', 'stup1d',
    'loser', 'l0ser', 'luser',
    'idiot', '1diot', 'id10t',
    'jerk', 'j3rk', 'jackass',
    'scumbag', 'douchebag', 'douche',
    'fuckhead', 'fuckface', 'fuckwit', 'fuckboy', 'fuckboi', 'fucknugget',
    'butthead', 'turd', 'twit', 'git', 'numpty',
    'prick', 'prik', 'schmuck',
    'weirdo', 'creep', 'perv', 'pervert',
    'rape', 'rapist', 'molest', 'molester',
    'pedophile', 'pedo',
    'porn', 'porno', 'pornography',
    'nude', 'nudes', 'naked',
    'tits', 'boobs', 'boob', 'boobies', 'nipple', 'nipples',
    'balls', 'testicle', 'testicles',
    'boner', 'erection', 'dildo', 'vibrator',
    'orgasm', 'fetish', 'kinky',
    'sodomy', 'incest', 'bestiality',
    'handjob', 'blowjob', 'rimjob', 'threesome', 'gangbang',
    'masturbate', 'masturbation',
    'jizz', 'sperm', 'semen', 'cum', 'cumshot', 'cumming',
    'horny', 'horndog',
    'twatwaffle', 'shitgibbon', 'assmonger', 'bellend',
    'nsfw',

    // Inggris - Frasa Ancaman
    'kill you', 'kill yourself', 'killyourself',
    'i will kill you',
    'go die', 'godie',
    'die bitch',
    'drop dead',
    'get fucked',

    // Inggris - Slur (Diskriminatif)
    'nigger', 'nigga', 'faggot', 'fag', 'retard', 'retarded', 'chink', 'spic', 'twat', 'wanker',
    'n1gger', 'n1gga', 'nigg3r', 'nigg4', 'nig', 'n.i.g.g.e.r',
    'f4ggot', 'fagg0t', 'f@ggot', 'f4g', 'f.a.g',
    'r3tard', 'ret4rd', 'r.e.t.a.r.d',
    'ch1nk', 'sp1c', 'tw@t', 'w4nker',
    'kike', 'k1ke', 'wetback', 'cracker', 'honky',
    'gook', 'slope', 'beaner',
    'tranny', 'trannie', 'dyke', 'lesbo',
    'homo', 'nazi', 'kkk',
    'raghead', 'towelhead', 'camel jockey',
    'zipperhead', 'jungle bunny', 'porch monkey',
    'coon', 'darkie', 'guido', 'wop', 'mick', 'kraut',

    // Gabungan/Campuran Internet
    'wtaf', 'wtfff', 'omfg', 'stfuu', 'gtfoh',
    'simp', 'simping', 'incel',
    'thot', 'hoe', 'skank', 'tramp', 'jezebel',
    'attention whore', 'clout chaser',
    'toxic', 'noob', 'n00b',
    'cope', 'mald', 'malding',
  ],
  scamWords: [
    // Nitro Scams & Fake Links
    'free nitro',
    'nitro free',
    'get nitro for free',
    'discord nitro gift',
    'discord-nitro',
    'dlscord',
    'dlsccord',
    'discord-app.com',
    'discrod',
    'discord-gift',
    'nitro-gift',
    'gift-nitro',
    'discord.com/billing', // Phishing link
    'discord-promotions',
    'discord-gg.com',
    'discord-events',

    // Crypto / Money Scams
    'free crypto',
    'free usdt',
    'giveaway usdt',
    'giving away $',
    'claim your reward',
    'claim reward',
    'receive usdt',
    'bonus usdt',
    'crypto giveaway',
    'send me eth',
    'send me btc',
    'double your money',
    'crypto casino',
    'airdrop',
    'connect wallet',
    
    // Gaming / Other Scams
    'steam 50$',
    'free steam games',
    'steamcommunity-gifts',
    'steam-promo',
    'steam-nitro',
    'free robux',
    'free vbucks',
    'genshin impact free primogems',
    'valorant free points',
    
    // General Scam Phrases
    'click here to claim',
    'register to get',
    'promo code',
    'giveaway winner',
    'you won a prize'
  ]
};